version: '3'

services:
    web:
        build: 
            context: ./docker
            dockerfile: Dockerfile-web
        volumes:
            - .:/home/web:ro
        command: python server.py
        restart: "always"
        ports: 
            - "8888:8888"
        user: web
        depends_on:
            - mysqldb
            - rabbitmq
        links:
            - mysqldb
            - rabbitmq
        networks:
            - default
    worker:
        build:
            context: ./docker
            dockerfile: Dockerfile-worker
        depends_on:
            - mysqldb
            - rabbitmq
        links:
            - mysqldb
            - rabbitmq
        depends_on:
            - mysqldb
            - rabbitmq
        networks:
            - default
    mysqldb:
        image: mysql:5.7
        expose: 
            - "3306"
        environment:
            MYSQL_DATABASE: uiharu
            MYSQL_USER: uiharu
            MYSQL_PASSWORD: uiharu
            MYSQL_ROOT_PASSWORD: uiharu 
        volumes:
            - ./schema:/docker-entrypoint-initdb.d
        networks:
            - default
    rabbitmq:
        image: rabbitmq:3.7
        networks:
            - default
